### ISSUE TITLE
asset-preview dir misspelled

### ISSUE THREAD

**Issue by mnutt** [FalconLee1011/Customized-Aerial-Screen-Saver#2]
https://github.com/FalconLee1011/Customized-Aerial-Screen-Saver/blob/1434f2d2dcce1cc2e62e9dbf19782ccb86fe2d0d/Customized%20Areal%20Screen%20Saver/CustomScreenSaverManager.swift#L58 has `asset-perview` instead of `asset-preview`.

**Comment by jtpotato** [comment]
@FalconLee1011 is it ok if I open a PR for this?

**Comment by FalconLee1011** [comment]
@mnutt Thanks for pointing out that mistake! Seems I really need some spell-checking pre-commit hook or something :p

@jtpotato Of course, PR is always welcomed:))

p.s. In this case, we need not only to correct the spelling, but also consider correcting existing path created.

**Comment by FalconLee1011** [comment]
Fixed in [version 1.1](https://github.com/FalconLee1011/Customized-Aerial-Screen-Saver/commit/962b2bd481c2c9737451c555d3c4b7b4a8083cb4) !
