### ISSUE TITLE
Won't show up in system settings

### ISSUE THREAD

**Issue by jessebarry2008** [FalconLee1011/Customized-Aerial-Screen-Saver#8]
Hi, I used the app to make a aerial wallpaper, and they update into finder, but I cannot select them in system settings. The app, everytime I open it, asks for my password as if I didn't put it in before (don't know if this is normal behaviour)

<img width="915" alt="Screenshot 2024-01-12 at 9 05 58 PM" src="https://github.com/FalconLee1011/Customized-Aerial-Screen-Saver/assets/82725749/e40e1c36-1d88-4c98-b4c2-10f06bfc611a">

https://github.com/FalconLee1011/Customized-Aerial-Screen-Saver/assets/82725749/20e49efe-7e6d-40f8-8453-da68e49b592d

<img width="763" alt="Screenshot 2024-01-12 at 9 07 18 PM" src="https://github.com/FalconLee1011/Customized-Aerial-Screen-Saver/assets/82725749/a5577dac-6a24-4e9d-a0b0-e8f9ed2511a3">

<img width="387" alt="Screenshot 2024-01-12 at 9 07 34 PM" src="https://github.com/FalconLee1011/Customized-Aerial-Screen-Saver/assets/82725749/6f42be9d-5088-4d92-a87c-01cb0a0b2cc8">

**Comment by kaghy** [comment]
Same here, video is the recommended settings (at least 15 seconds, 60 fps, above 1920x1080, etc....) but no dice.

Now I know there is an issue with the database to update, but I've tried multiple times to use a video.

My first failed attempt, the thumbnail was there for at least a day..... and after that no updates on the screensaver screen.

**Comment by SteveKueng** [comment]
According to my tests, the following command leads to an automatic update of the database and also an update in the system settings:
killall idleassetsd 

@FalconLee1011 maybe you can integrate this

**Comment by kaghy** [comment]
> According to my tests, the following command leads to an automatic update of the database and also an update in the system settings: killall idleassetsd
> 
> @FalconLee1011 maybe you can integrate this

No dice here...

**Comment by ywjung328** [comment]
> > According to my tests, the following command leads to an automatic update of the database and also an update in the system settings: killall idleassetsd
> > @FalconLee1011 maybe you can integrate this
> 
> No dice here...

You can delete db files (Aerial.sqlite, Aerial.sqlite-shm, Aerial.sqlite-wal) and then kill the process. That will trigger the spawning process to rebuild the database. But as always, since those files are system files, backup first.

@FalconLee1011 Wondering if this process can be integrated into your app.

**Comment by FalconLee1011** [comment]
Fixed in #962b2bd481c2c9737451c555d3c4b7b4a8083cb4 !
